apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: restapi
  name: restapi
  namespace: restapi 
spec:
  type: {{ .Values.restapi.servicetype }}
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: restapi
status:
  loadBalancer: {}
